apiVersion: v1
kind: Secret
metadata:
  name: eventhub-app-secrets
  namespace: eventhub
type: Opaque
stringData:
  JWT_SECRET: change-me
  REFRESH_TOKEN_SECRET: change-me-too
  POSTGRES_PASSWORD: eventhub123
